/* INSERT QUERY */
INSERT INTO PROMO_PRODUK(id_promo, kode_produk)
VALUES
('R00001', 'P0000091');
/* INSERT QUERY */
INSERT INTO PROMO_PRODUK(id_promo, kode_produk)
VALUES
('R00001', 'P0000123');
/* INSERT QUERY */
INSERT INTO PROMO_PRODUK(id_promo, kode_produk)
VALUES
('R00005', 'P0000031');
/* INSERT QUERY */
INSERT INTO PROMO_PRODUK(id_promo, kode_produk)
VALUES
('R00003', 'SK006');
/* INSERT QUERY */
INSERT INTO PROMO_PRODUK(id_promo, kode_produk)
VALUES
('R00003', 'P0000138');
/* INSERT QUERY */
INSERT INTO PROMO_PRODUK(id_promo, kode_produk)
VALUES
('R00003', 'P0000081');
/* INSERT QUERY */
INSERT INTO PROMO_PRODUK(id_promo, kode_produk)
VALUES
('R00001', 'SK019');
/* INSERT QUERY */
INSERT INTO PROMO_PRODUK(id_promo, kode_produk)
VALUES
('R00002', 'P0000040');
/* INSERT QUERY */
INSERT INTO PROMO_PRODUK(id_promo, kode_produk)
VALUES
('R00001', 'P0000041');
/* INSERT QUERY */
INSERT INTO PROMO_PRODUK(id_promo, kode_produk)
VALUES
('R00002', 'P0000061');
/* INSERT QUERY */
INSERT INTO PROMO_PRODUK(id_promo, kode_produk)
VALUES
('R00001', 'SK034');
/* INSERT QUERY */
INSERT INTO PROMO_PRODUK(id_promo, kode_produk)
VALUES
('R00003', 'SK119');
/* INSERT QUERY */
INSERT INTO PROMO_PRODUK(id_promo, kode_produk)
VALUES
('R00001', 'SK085');
/* INSERT QUERY */
INSERT INTO PROMO_PRODUK(id_promo, kode_produk)
VALUES
('R00003', 'P0000096');
/* INSERT QUERY */
INSERT INTO PROMO_PRODUK(id_promo, kode_produk)
VALUES
('R00005', 'SK162');
/* INSERT QUERY */
INSERT INTO PROMO_PRODUK(id_promo, kode_produk)
VALUES
('R00002', 'SK015');
/* INSERT QUERY */
INSERT INTO PROMO_PRODUK(id_promo, kode_produk)
VALUES
('R00003', 'SK056');
/* INSERT QUERY */
INSERT INTO PROMO_PRODUK(id_promo, kode_produk)
VALUES
('R00005', 'P0000121');
/* INSERT QUERY */
INSERT INTO PROMO_PRODUK(id_promo, kode_produk)
VALUES
('R00002', 'P0000097');
/* INSERT QUERY */
INSERT INTO PROMO_PRODUK(id_promo, kode_produk)
VALUES
('R00004', 'P0000074');
/* INSERT QUERY */
INSERT INTO PROMO_PRODUK(id_promo, kode_produk)
VALUES
('R00004', 'P0000176');
/* INSERT QUERY */
INSERT INTO PROMO_PRODUK(id_promo, kode_produk)
VALUES
('R00004', 'SK019');
/* INSERT QUERY */
INSERT INTO PROMO_PRODUK(id_promo, kode_produk)
VALUES
('R00002', 'SK002');
/* INSERT QUERY */
INSERT INTO PROMO_PRODUK(id_promo, kode_produk)
VALUES
('R00004', 'P0000088');
/* INSERT QUERY */
INSERT INTO PROMO_PRODUK(id_promo, kode_produk)
VALUES
('R00003', 'SK097');
/* INSERT QUERY */
INSERT INTO PROMO_PRODUK(id_promo, kode_produk)
VALUES
('R00005', 'SK142');
/* INSERT QUERY */
INSERT INTO PROMO_PRODUK(id_promo, kode_produk)
VALUES
('R00003', 'P0000038');
/* INSERT QUERY */
INSERT INTO PROMO_PRODUK(id_promo, kode_produk)
VALUES
('R00003', 'SK167');
/* INSERT QUERY */
INSERT INTO PROMO_PRODUK(id_promo, kode_produk)
VALUES
('R00002', 'P0000102');
/* INSERT QUERY */
INSERT INTO PROMO_PRODUK(id_promo, kode_produk)
VALUES
('R00005', 'SK070');
/* INSERT QUERY */
INSERT INTO PROMO_PRODUK(id_promo, kode_produk)
VALUES
('R00003', 'SK036');
/* INSERT QUERY */
INSERT INTO PROMO_PRODUK(id_promo, kode_produk)
VALUES
('R00002', 'SK092');
/* INSERT QUERY */
INSERT INTO PROMO_PRODUK(id_promo, kode_produk)
VALUES
('R00001', 'P0000178');
/* INSERT QUERY */
INSERT INTO PROMO_PRODUK(id_promo, kode_produk)
VALUES
('R00003', 'SK051');
/* INSERT QUERY */
INSERT INTO PROMO_PRODUK(id_promo, kode_produk)
VALUES
('R00001', 'P0000078');
/* INSERT QUERY */
INSERT INTO PROMO_PRODUK(id_promo, kode_produk)
VALUES
('R00001', 'SK056');
/* INSERT QUERY */
INSERT INTO PROMO_PRODUK(id_promo, kode_produk)
VALUES
('R00003', 'P0000200');
/* INSERT QUERY */
INSERT INTO PROMO_PRODUK(id_promo, kode_produk)
VALUES
('R00002', 'SK008');
/* INSERT QUERY */
INSERT INTO PROMO_PRODUK(id_promo, kode_produk)
VALUES
('R00002', 'P0000160');
/* INSERT QUERY */
INSERT INTO PROMO_PRODUK(id_promo, kode_produk)
VALUES
('R00005', 'SK177');
/* INSERT QUERY */
INSERT INTO PROMO_PRODUK(id_promo, kode_produk)
VALUES
('R00005', 'SK163');
/* INSERT QUERY */
INSERT INTO PROMO_PRODUK(id_promo, kode_produk)
VALUES
('R00003', 'P0000143');
/* INSERT QUERY */
INSERT INTO PROMO_PRODUK(id_promo, kode_produk)
VALUES
('R00002', 'SK062');
/* INSERT QUERY */
INSERT INTO PROMO_PRODUK(id_promo, kode_produk)
VALUES
('R00005', 'SK084');
/* INSERT QUERY */
INSERT INTO PROMO_PRODUK(id_promo, kode_produk)
VALUES
('R00005', 'P0000080');
/* INSERT QUERY */
INSERT INTO PROMO_PRODUK(id_promo, kode_produk)
VALUES
('R00002', 'SK162');
/* INSERT QUERY */
INSERT INTO PROMO_PRODUK(id_promo, kode_produk)
VALUES
('R00001', 'SK158');
/* INSERT QUERY */
INSERT INTO PROMO_PRODUK(id_promo, kode_produk)
VALUES
('R00003', 'P0000191');
/* INSERT QUERY */
INSERT INTO PROMO_PRODUK(id_promo, kode_produk)
VALUES
('R00002', 'SK106');
/* INSERT QUERY */
INSERT INTO PROMO_PRODUK(id_promo, kode_produk)
VALUES
('R00004', 'P0000116');
/* INSERT QUERY */
INSERT INTO PROMO_PRODUK(id_promo, kode_produk)
VALUES
('R00002', 'SK107');
/* INSERT QUERY */
INSERT INTO PROMO_PRODUK(id_promo, kode_produk)
VALUES
('R00004', 'SK084');
/* INSERT QUERY */
INSERT INTO PROMO_PRODUK(id_promo, kode_produk)
VALUES
('R00002', 'P0000144');
/* INSERT QUERY */
INSERT INTO PROMO_PRODUK(id_promo, kode_produk)
VALUES
('R00003', 'SK057');
/* INSERT QUERY */
INSERT INTO PROMO_PRODUK(id_promo, kode_produk)
VALUES
('R00002', 'P0000132');
/* INSERT QUERY */
INSERT INTO PROMO_PRODUK(id_promo, kode_produk)
VALUES
('R00005', 'P0000118');
/* INSERT QUERY */
INSERT INTO PROMO_PRODUK(id_promo, kode_produk)
VALUES
('R00002', 'SK163');
/* INSERT QUERY */
INSERT INTO PROMO_PRODUK(id_promo, kode_produk)
VALUES
('R00002', 'SK174');
/* INSERT QUERY */
INSERT INTO PROMO_PRODUK(id_promo, kode_produk)
VALUES
('R00005', 'SK082');
/* INSERT QUERY */
INSERT INTO PROMO_PRODUK(id_promo, kode_produk)
VALUES
('R00004', 'SK208');
/* INSERT QUERY */
INSERT INTO PROMO_PRODUK(id_promo, kode_produk)
VALUES
('R00005', 'P0000199');
/* INSERT QUERY */
INSERT INTO PROMO_PRODUK(id_promo, kode_produk)
VALUES
('R00004', 'P0000198');
/* INSERT QUERY */
INSERT INTO PROMO_PRODUK(id_promo, kode_produk)
VALUES
('R00004', 'SK085');
/* INSERT QUERY */
INSERT INTO PROMO_PRODUK(id_promo, kode_produk)
VALUES
('R00001', 'SK150');
/* INSERT QUERY */
INSERT INTO PROMO_PRODUK(id_promo, kode_produk)
VALUES
('R00005', 'SK065');
/* INSERT QUERY */
INSERT INTO PROMO_PRODUK(id_promo, kode_produk)
VALUES
('R00005', 'SK120');
/* INSERT QUERY */
INSERT INTO PROMO_PRODUK(id_promo, kode_produk)
VALUES
('R00002', 'SK207');
/* INSERT QUERY */
INSERT INTO PROMO_PRODUK(id_promo, kode_produk)
VALUES
('R00002', 'SK011');
/* INSERT QUERY */
INSERT INTO PROMO_PRODUK(id_promo, kode_produk)
VALUES
('R00003', 'SK170');
/* INSERT QUERY */
INSERT INTO PROMO_PRODUK(id_promo, kode_produk)
VALUES
('R00003', 'SK013');
/* INSERT QUERY */
INSERT INTO PROMO_PRODUK(id_promo, kode_produk)
VALUES
('R00002', 'SK098');
/* INSERT QUERY */
INSERT INTO PROMO_PRODUK(id_promo, kode_produk)
VALUES
('R00001', 'SK060');
/* INSERT QUERY */
INSERT INTO PROMO_PRODUK(id_promo, kode_produk)
VALUES
('R00003', 'P0000088');
/* INSERT QUERY */
INSERT INTO PROMO_PRODUK(id_promo, kode_produk)
VALUES
('R00005', 'SK072');
/* INSERT QUERY */
INSERT INTO PROMO_PRODUK(id_promo, kode_produk)
VALUES
('R00005', 'SK064');
